#!/bin/sh

# usage: ./gen
currentDir=$(PWD)

rm -f $currentDir/xml/*/model.go

for f in $currentDir/xsd/*.xsd ; do
    echo "$f"
    filename=$(basename $f)
    filenamenoextension="${filename%.*}"
    filenamenoextension2="${filenamenoextension//./_}"
    cmd="xgen -l Go -i $f -t Xml -o $currentDir/xml/$filenamenoextension2/model.go -p $filenamenoextension2"
    echo $cmd
    eval $cmd
done
