// Code generated by xgen. DO NOT EDIT.

package head_001_001_01

// AppHdr ...
type AppHdr *BusinessApplicationHeaderV01

// AddressType2Code ...
type AddressType2Code string

// AnyBICIdentifier ...
type AnyBICIdentifier string

// BICFIIdentifier ...
type BICFIIdentifier string

// BranchAndFinancialInstitutionIdentification5 ...
type BranchAndFinancialInstitutionIdentification5 struct {
	FinInstnId *FinancialInstitutionIdentification8 `json:"FinInstnId"`
	BrnchId    *BranchData2                         `json:"BrnchId"`
}

// BranchData2 ...
type BranchData2 struct {
	Id      string          `json:"Id"`
	Nm      string          `json:"Nm"`
	PstlAdr *PostalAddress6 `json:"PstlAdr"`
}

// BusinessApplicationHeader1 ...
type BusinessApplicationHeader1 struct {
	CharSet    string             `json:"CharSet"`
	Fr         *Party9Choice      `json:"Fr"`
	To         *Party9Choice      `json:"To"`
	BizMsgIdr  string             `json:"BizMsgIdr"`
	MsgDefIdr  string             `json:"MsgDefIdr"`
	BizSvc     string             `json:"BizSvc"`
	CreDt      string             `json:"CreDt"`
	CpyDplct   string             `json:"CpyDplct"`
	PssblDplct bool               `json:"PssblDplct"`
	Prty       string             `json:"Prty"`
	Sgntr      *SignatureEnvelope `json:"Sgntr"`
}

// BusinessApplicationHeaderV01 ...
type BusinessApplicationHeaderV01 struct {
	CharSet    string                      `json:"CharSet"`
	Fr         *Party9Choice               `json:"Fr"`
	To         *Party9Choice               `json:"To"`
	BizMsgIdr  string                      `json:"BizMsgIdr"`
	MsgDefIdr  string                      `json:"MsgDefIdr"`
	BizSvc     string                      `json:"BizSvc"`
	CreDt      string                      `json:"CreDt"`
	CpyDplct   string                      `json:"CpyDplct"`
	PssblDplct bool                        `json:"PssblDplct"`
	Prty       string                      `json:"Prty"`
	Sgntr      *SignatureEnvelope          `json:"Sgntr"`
	Rltd       *BusinessApplicationHeader1 `json:"Rltd"`
}

// BusinessMessagePriorityCode ...
type BusinessMessagePriorityCode string

// ClearingSystemIdentification2Choice ...
type ClearingSystemIdentification2Choice struct {
	Cd    string `json:"Cd"`
	Prtry string `json:"Prtry"`
}

// ClearingSystemMemberIdentification2 ...
type ClearingSystemMemberIdentification2 struct {
	ClrSysId *ClearingSystemIdentification2Choice `json:"ClrSysId"`
	MmbId    string                               `json:"MmbId"`
}

// ContactDetails2 ...
type ContactDetails2 struct {
	NmPrfx   string `json:"NmPrfx"`
	Nm       string `json:"Nm"`
	PhneNb   string `json:"PhneNb"`
	MobNb    string `json:"MobNb"`
	FaxNb    string `json:"FaxNb"`
	EmailAdr string `json:"EmailAdr"`
	Othr     string `json:"Othr"`
}

// CopyDuplicate1Code ...
type CopyDuplicate1Code string

// CountryCode ...
type CountryCode string

// DateAndPlaceOfBirth ...
type DateAndPlaceOfBirth struct {
	BirthDt     string `json:"BirthDt"`
	PrvcOfBirth string `json:"PrvcOfBirth"`
	CityOfBirth string `json:"CityOfBirth"`
	CtryOfBirth string `json:"CtryOfBirth"`
}

// ExternalClearingSystemIdentification1Code ...
type ExternalClearingSystemIdentification1Code string

// ExternalFinancialInstitutionIdentification1Code ...
type ExternalFinancialInstitutionIdentification1Code string

// ExternalOrganisationIdentification1Code ...
type ExternalOrganisationIdentification1Code string

// ExternalPersonIdentification1Code ...
type ExternalPersonIdentification1Code string

// FinancialIdentificationSchemeName1Choice ...
type FinancialIdentificationSchemeName1Choice struct {
	Cd    string `json:"Cd"`
	Prtry string `json:"Prtry"`
}

// FinancialInstitutionIdentification8 ...
type FinancialInstitutionIdentification8 struct {
	BICFI       string                               `json:"BICFI"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `json:"ClrSysMmbId"`
	Nm          string                               `json:"Nm"`
	PstlAdr     *PostalAddress6                      `json:"PstlAdr"`
	Othr        *GenericFinancialIdentification1     `json:"Othr"`
}

// GenericFinancialIdentification1 ...
type GenericFinancialIdentification1 struct {
	Id      string                                    `json:"Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `json:"SchmeNm"`
	Issr    string                                    `json:"Issr"`
}

// GenericOrganisationIdentification1 ...
type GenericOrganisationIdentification1 struct {
	Id      string                                       `json:"Id"`
	SchmeNm *OrganisationIdentificationSchemeName1Choice `json:"SchmeNm"`
	Issr    string                                       `json:"Issr"`
}

// GenericPersonIdentification1 ...
type GenericPersonIdentification1 struct {
	Id      string                                 `json:"Id"`
	SchmeNm *PersonIdentificationSchemeName1Choice `json:"SchmeNm"`
	Issr    string                                 `json:"Issr"`
}

// ISODate ...
type ISODate string

// ISONormalisedDateTime ...
type ISONormalisedDateTime string

// Max140Text ...
type Max140Text string

// Max16Text ...
type Max16Text string

// Max2048Text ...
type Max2048Text string

// Max35Text ...
type Max35Text string

// Max70Text ...
type Max70Text string

// NamePrefix1Code ...
type NamePrefix1Code string

// OrganisationIdentification7 ...
type OrganisationIdentification7 struct {
	AnyBIC string                                `json:"AnyBIC"`
	Othr   []*GenericOrganisationIdentification1 `json:"Othr"`
}

// OrganisationIdentificationSchemeName1Choice ...
type OrganisationIdentificationSchemeName1Choice struct {
	Cd    string `json:"Cd"`
	Prtry string `json:"Prtry"`
}

// Party10Choice ...
type Party10Choice struct {
	OrgId  *OrganisationIdentification7 `json:"OrgId"`
	PrvtId *PersonIdentification5       `json:"PrvtId"`
}

// Party9Choice ...
type Party9Choice struct {
	OrgId *PartyIdentification42                        `json:"OrgId"`
	FIId  *BranchAndFinancialInstitutionIdentification5 `json:"FIId"`
}

// PartyIdentification42 ...
type PartyIdentification42 struct {
	Nm        string           `json:"Nm"`
	PstlAdr   *PostalAddress6  `json:"PstlAdr"`
	Id        *Party10Choice   `json:"Id"`
	CtryOfRes string           `json:"CtryOfRes"`
	CtctDtls  *ContactDetails2 `json:"CtctDtls"`
}

// PersonIdentification5 ...
type PersonIdentification5 struct {
	DtAndPlcOfBirth *DateAndPlaceOfBirth            `json:"DtAndPlcOfBirth"`
	Othr            []*GenericPersonIdentification1 `json:"Othr"`
}

// PersonIdentificationSchemeName1Choice ...
type PersonIdentificationSchemeName1Choice struct {
	Cd    string `json:"Cd"`
	Prtry string `json:"Prtry"`
}

// PhoneNumber ...
type PhoneNumber string

// PostalAddress6 ...
type PostalAddress6 struct {
	AdrTp       string   `json:"AdrTp"`
	Dept        string   `json:"Dept"`
	SubDept     string   `json:"SubDept"`
	StrtNm      string   `json:"StrtNm"`
	BldgNb      string   `json:"BldgNb"`
	PstCd       string   `json:"PstCd"`
	TwnNm       string   `json:"TwnNm"`
	CtrySubDvsn string   `json:"CtrySubDvsn"`
	Ctry        string   `json:"Ctry"`
	AdrLine     []string `json:"AdrLine"`
}

// SignatureEnvelope ...
type SignatureEnvelope struct {
}

// UnicodeChartsCode ...
type UnicodeChartsCode string

// YesNoIndicator ...
type YesNoIndicator bool
