// Code generated by xgen. DO NOT EDIT.

package cain_004_001_01

import (
	"encoding/xml"
)

// Document ...
type Document *Document

// AccountIdentification30Choice ...
type AccountIdentification30Choice struct {
	XMLName *xml.Name `xml:"AccountIdentification30Choice"`
	Card    string    `xml:"Card"`
	MSISDN  string    `xml:"MSISDN"`
	EMail   string    `xml:"EMail"`
	IBAN    string    `xml:"IBAN"`
	BBAN    string    `xml:"BBAN"`
	UPIC    string    `xml:"UPIC"`
	Dmst    string    `xml:"Dmst"`
	Othr    string    `xml:"Othr"`
}

// AcquirerFinancialResponse ...
type AcquirerFinancialResponse struct {
	XMLName  *xml.Name                   `xml:"AcquirerFinancialResponse"`
	Hdr      *Header17                   `xml:"Hdr"`
	FinRspn  *AcquirerFinancialResponse1 `xml:"FinRspn"`
	SctyTrlr *ContentInformationType15   `xml:"SctyTrlr"`
}

// AcquirerFinancialResponse1 ...
type AcquirerFinancialResponse1 struct {
	XMLName *xml.Name                    `xml:"AcquirerFinancialResponse1"`
	Envt    *CardTransactionEnvironment2 `xml:"Envt"`
	Cntxt   *CardTransactionContext3     `xml:"Cntxt"`
	Tx      *CardTransaction6            `xml:"Tx"`
}

// Action4 ...
type Action4 struct {
	XMLName   *xml.Name       `xml:"Action4"`
	ActnTp    string          `xml:"ActnTp"`
	MsgToPres *ActionMessage2 `xml:"MsgToPres"`
}

// ActionMessage2 ...
type ActionMessage2 struct {
	XMLName      *xml.Name `xml:"ActionMessage2"`
	MsgDstn      string    `xml:"MsgDstn"`
	Frmt         string    `xml:"Frmt"`
	MsgCntt      string    `xml:"MsgCntt"`
	MsgCnttSgntr string    `xml:"MsgCnttSgntr"`
}

// ActionMessage3 ...
type ActionMessage3 struct {
	XMLName *xml.Name `xml:"ActionMessage3"`
	Dstn    string    `xml:"Dstn"`
	Frmt    string    `xml:"Frmt"`
	Cntt    string    `xml:"Cntt"`
}

// ActionType5Code ...
type ActionType5Code string

// ActiveCurrencyCode ...
type ActiveCurrencyCode string

// AddressType2Code ...
type AddressType2Code string

// Algorithm11Code ...
type Algorithm11Code string

// Algorithm12Code ...
type Algorithm12Code string

// Algorithm13Code ...
type Algorithm13Code string

// Algorithm15Code ...
type Algorithm15Code string

// Algorithm7Code ...
type Algorithm7Code string

// Algorithm8Code ...
type Algorithm8Code string

// AlgorithmIdentification11 ...
type AlgorithmIdentification11 struct {
	XMLName *xml.Name   `xml:"AlgorithmIdentification11"`
	Algo    string      `xml:"Algo"`
	Param   *Parameter4 `xml:"Param"`
}

// AlgorithmIdentification12 ...
type AlgorithmIdentification12 struct {
	XMLName *xml.Name   `xml:"AlgorithmIdentification12"`
	Algo    string      `xml:"Algo"`
	Param   *Parameter5 `xml:"Param"`
}

// AlgorithmIdentification13 ...
type AlgorithmIdentification13 struct {
	XMLName *xml.Name   `xml:"AlgorithmIdentification13"`
	Algo    string      `xml:"Algo"`
	Param   *Parameter6 `xml:"Param"`
}

// AlgorithmIdentification14 ...
type AlgorithmIdentification14 struct {
	XMLName *xml.Name   `xml:"AlgorithmIdentification14"`
	Algo    string      `xml:"Algo"`
	Param   *Parameter6 `xml:"Param"`
}

// AlgorithmIdentification15 ...
type AlgorithmIdentification15 struct {
	XMLName *xml.Name   `xml:"AlgorithmIdentification15"`
	Algo    string      `xml:"Algo"`
	Param   *Parameter7 `xml:"Param"`
}

// AmountAndDirection41 ...
type AmountAndDirection41 struct {
	XMLName *xml.Name          `xml:"AmountAndDirection41"`
	Amt     *CurrencyAndAmount `xml:"Amt"`
	Sgn     bool               `xml:"Sgn"`
}

// AnyBICIdentifier ...
type AnyBICIdentifier string

// AttributeType1Code ...
type AttributeType1Code string

// AuthenticatedData4 ...
type AuthenticatedData4 struct {
	XMLName     *xml.Name                  `xml:"AuthenticatedData4"`
	Vrsn        float64                    `xml:"Vrsn"`
	Rcpt        []*Recipient4Choice        `xml:"Rcpt"`
	MACAlgo     *AlgorithmIdentification15 `xml:"MACAlgo"`
	NcpsltdCntt *EncapsulatedContent3      `xml:"NcpsltdCntt"`
	MAC         string                     `xml:"MAC"`
}

// AuthenticationEntity2Code ...
type AuthenticationEntity2Code string

// AuthenticationMethod6Code ...
type AuthenticationMethod6Code string

// AuthorisationResult8 ...
type AuthorisationResult8 struct {
	XMLName     *xml.Name                `xml:"AuthorisationResult8"`
	AuthstnNtty *GenericIdentification75 `xml:"AuthstnNtty"`
	TxRspn      *ResponseType2           `xml:"TxRspn"`
	Actn        []*Action4               `xml:"Actn"`
	AuthstnCd   string                   `xml:"AuthstnCd"`
	AddtlInf    []*ActionMessage3        `xml:"AddtlInf"`
}

// BBANIdentifier ...
type BBANIdentifier string

// BaseOneRate ...
type BaseOneRate float64

// BytePadding1Code ...
type BytePadding1Code string

// CardAccount2 ...
type CardAccount2 struct {
	XMLName      *xml.Name                      `xml:"CardAccount2"`
	SelctdAcctTp string                         `xml:"SelctdAcctTp"`
	AcctNm       string                         `xml:"AcctNm"`
	AcctOwnr     *NameAndAddress3               `xml:"AcctOwnr"`
	Ccy          string                         `xml:"Ccy"`
	AcctIdr      *AccountIdentification30Choice `xml:"AcctIdr"`
	Svcr         *PartyIdentification72Choice   `xml:"Svcr"`
	Bal          *AmountAndDirection41          `xml:"Bal"`
	BalDt        string                         `xml:"BalDt"`
}

// CardAccountType2Code ...
type CardAccountType2Code string

// CardPaymentServiceType7Code ...
type CardPaymentServiceType7Code string

// CardPaymentToken2 ...
type CardPaymentToken2 struct {
	XMLName      *xml.Name `xml:"CardPaymentToken2"`
	TknChrtc     []string  `xml:"TknChrtc"`
	TknAssrncLvl float64   `xml:"TknAssrncLvl"`
}

// CardProductType1Code ...
type CardProductType1Code string

// CardTransaction6 ...
type CardTransaction6 struct {
	XMLName           *xml.Name               `xml:"CardTransaction6"`
	TxTp              string                  `xml:"TxTp"`
	Rcncltn           *TransactionIdentifier2 `xml:"Rcncltn"`
	AccptrTxDtTm      string                  `xml:"AccptrTxDtTm"`
	InitrTxId         string                  `xml:"InitrTxId"`
	TxLifeCyclId      string                  `xml:"TxLifeCyclId"`
	TxLifeCyclSeqNb   float64                 `xml:"TxLifeCyclSeqNb"`
	TxLifeCyclSeqCntr float64                 `xml:"TxLifeCyclSeqCntr"`
	CardIssrRefData   string                  `xml:"CardIssrRefData"`
	TxDtls            *CardTransactionDetail4 `xml:"TxDtls"`
	AuthstnRslt       *AuthorisationResult8   `xml:"AuthstnRslt"`
}

// CardTransactionAmount4 ...
type CardTransactionAmount4 struct {
	XMLName          *xml.Name          `xml:"CardTransactionAmount4"`
	TtlAmt           *CurrencyAndAmount `xml:"TtlAmt"`
	CrdhldrBllgTxAmt *DetailedAmount8   `xml:"CrdhldrBllgTxAmt"`
	RcncltnTxAmt     *DetailedAmount8   `xml:"RcncltnTxAmt"`
	DtldAmt          []*DetailedAmount9 `xml:"DtldAmt"`
}

// CardTransactionCondition1 ...
type CardTransactionCondition1 struct {
	XMLName *xml.Name `xml:"CardTransactionCondition1"`
	Prgm    string    `xml:"Prgm"`
	Val     string    `xml:"Val"`
}

// CardTransactionContext3 ...
type CardTransactionContext3 struct {
	XMLName *xml.Name                `xml:"CardTransactionContext3"`
	TxCntxt *CardTransactionContext4 `xml:"TxCntxt"`
}

// CardTransactionContext4 ...
type CardTransactionContext4 struct {
	XMLName   *xml.Name                    `xml:"CardTransactionContext4"`
	SpclConds []*CardTransactionCondition1 `xml:"SpclConds"`
}

// CardTransactionDetail4 ...
type CardTransactionDetail4 struct {
	XMLName      *xml.Name                         `xml:"CardTransactionDetail4"`
	TxAmts       *CardTransactionAmount4           `xml:"TxAmts"`
	TxFees       []*DetailedAmount11               `xml:"TxFees"`
	AddtlAmts    []*DetailedAmount10               `xml:"AddtlAmts"`
	AcctAndBal   []*CardAccount2                   `xml:"AcctAndBal"`
	TxVrfctnRslt []*TransactionVerificationResult4 `xml:"TxVrfctnRslt"`
	VldtyDt      string                            `xml:"VldtyDt"`
	ICCRltdData  string                            `xml:"ICCRltdData"`
}

// CardTransactionEnvironment2 ...
type CardTransactionEnvironment2 struct {
	XMLName     *xml.Name          `xml:"CardTransactionEnvironment2"`
	AcqrrId     string             `xml:"AcqrrId"`
	CardSchmeId string             `xml:"CardSchmeId"`
	AccptrId    string             `xml:"AccptrId"`
	TermnlId    string             `xml:"TermnlId"`
	Card        *PaymentCard13     `xml:"Card"`
	PmtTkn      *CardPaymentToken2 `xml:"PmtTkn"`
	ShppgAdr    *PostalAddress18   `xml:"ShppgAdr"`
}

// CertificateIssuer1 ...
type CertificateIssuer1 struct {
	XMLName        *xml.Name                     `xml:"CertificateIssuer1"`
	RltvDstngshdNm []*RelativeDistinguishedName1 `xml:"RltvDstngshdNm"`
}

// ContentInformationType10 ...
type ContentInformationType10 struct {
	XMLName    *xml.Name       `xml:"ContentInformationType10"`
	CnttTp     string          `xml:"CnttTp"`
	EnvlpdData *EnvelopedData4 `xml:"EnvlpdData"`
}

// ContentInformationType15 ...
type ContentInformationType15 struct {
	XMLName      *xml.Name           `xml:"ContentInformationType15"`
	CnttTp       string              `xml:"CnttTp"`
	AuthntcdData *AuthenticatedData4 `xml:"AuthntcdData"`
}

// ContentType2Code ...
type ContentType2Code string

// CountryCode ...
type CountryCode string

// CurrencyAndAmountSimpleType ...
type CurrencyAndAmountSimpleType float64

// CurrencyAndAmount ...
type CurrencyAndAmount struct {
	XMLName *xml.Name `xml:"CurrencyAndAmount"`
	CcyAttr string    `json:"-,omitempty", bson:"-,omitempty", xml:"Ccy,attr"`
	Value   float64   `xml:",chardata"`
}

// CurrencyCode ...
type CurrencyCode string

// DetailedAmount10 ...
type DetailedAmount10 struct {
	XMLName *xml.Name          `xml:"DetailedAmount10"`
	Tp      string             `xml:"Tp"`
	AddtlTp string             `xml:"AddtlTp"`
	Amt     *CurrencyAndAmount `xml:"Amt"`
	Labl    string             `xml:"Labl"`
}

// DetailedAmount11 ...
type DetailedAmount11 struct {
	XMLName  *xml.Name             `xml:"DetailedAmount11"`
	Tp       string                `xml:"Tp"`
	AddtlTp  string                `xml:"AddtlTp"`
	Amt      *AmountAndDirection41 `xml:"Amt"`
	OrgnlAmt *AmountAndDirection41 `xml:"OrgnlAmt"`
}

// DetailedAmount8 ...
type DetailedAmount8 struct {
	XMLName  *xml.Name `xml:"DetailedAmount8"`
	Amt      float64   `xml:"Amt"`
	XchgRate float64   `xml:"XchgRate"`
	QtnDt    string    `xml:"QtnDt"`
	Labl     string    `xml:"Labl"`
}

// DetailedAmount9 ...
type DetailedAmount9 struct {
	XMLName *xml.Name `xml:"DetailedAmount9"`
	Tp      string    `xml:"Tp"`
	AddtlTp string    `xml:"AddtlTp"`
	Amt     float64   `xml:"Amt"`
	Labl    string    `xml:"Labl"`
}

// EncapsulatedContent3 ...
type EncapsulatedContent3 struct {
	XMLName *xml.Name `xml:"EncapsulatedContent3"`
	CnttTp  string    `xml:"CnttTp"`
	Cntt    string    `xml:"Cntt"`
}

// EncryptedContent3 ...
type EncryptedContent3 struct {
	XMLName        *xml.Name                  `xml:"EncryptedContent3"`
	CnttTp         string                     `xml:"CnttTp"`
	CnttNcrptnAlgo *AlgorithmIdentification14 `xml:"CnttNcrptnAlgo"`
	NcrptdData     string                     `xml:"NcrptdData"`
}

// EncryptionFormat1Code ...
type EncryptionFormat1Code string

// EnvelopedData4 ...
type EnvelopedData4 struct {
	XMLName    *xml.Name           `xml:"EnvelopedData4"`
	Vrsn       float64             `xml:"Vrsn"`
	Rcpt       []*Recipient4Choice `xml:"Rcpt"`
	NcrptdCntt *EncryptedContent3  `xml:"NcrptdCntt"`
}

// Exact1NumericText ...
type Exact1NumericText string

// Exact3NumericText ...
type Exact3NumericText string

// GenericIdentification1 ...
type GenericIdentification1 struct {
	XMLName *xml.Name `xml:"GenericIdentification1"`
	Id      string    `xml:"Id"`
	SchmeNm string    `xml:"SchmeNm"`
	Issr    string    `xml:"Issr"`
}

// GenericIdentification73 ...
type GenericIdentification73 struct {
	XMLName *xml.Name `xml:"GenericIdentification73"`
	Id      string    `xml:"Id"`
	Tp      string    `xml:"Tp"`
	Issr    string    `xml:"Issr"`
	Ctry    string    `xml:"Ctry"`
	ShrtNm  string    `xml:"ShrtNm"`
}

// GenericIdentification74 ...
type GenericIdentification74 struct {
	XMLName *xml.Name `xml:"GenericIdentification74"`
	Id      string    `xml:"Id"`
	Tp      string    `xml:"Tp"`
	Issr    string    `xml:"Issr"`
	Ctry    string    `xml:"Ctry"`
	ShrtNm  string    `xml:"ShrtNm"`
}

// GenericIdentification75 ...
type GenericIdentification75 struct {
	XMLName *xml.Name `xml:"GenericIdentification75"`
	Id      string    `xml:"Id"`
	Tp      string    `xml:"Tp"`
	Issr    string    `xml:"Issr"`
	Ctry    string    `xml:"Ctry"`
	ShrtNm  string    `xml:"ShrtNm"`
}

// Header17 ...
type Header17 struct {
	XMLName        *xml.Name                `xml:"Header17"`
	MsgFctn        string                   `xml:"MsgFctn"`
	PrtcolVrsn     string                   `xml:"PrtcolVrsn"`
	XchgId         string                   `xml:"XchgId"`
	ReTrnsmssnCntr string                   `xml:"ReTrnsmssnCntr"`
	CreDtTm        string                   `xml:"CreDtTm"`
	InitgPty       *GenericIdentification73 `xml:"InitgPty"`
	RcptPty        *GenericIdentification73 `xml:"RcptPty"`
	Tracblt        []*Traceability3         `xml:"Tracblt"`
}

// IBANIdentifier ...
type IBANIdentifier string

// ISODate ...
type ISODate string

// ISODateTime ...
type ISODateTime string

// ImpliedCurrencyAndAmount ...
type ImpliedCurrencyAndAmount float64

// IssuerAndSerialNumber1 ...
type IssuerAndSerialNumber1 struct {
	XMLName *xml.Name           `xml:"IssuerAndSerialNumber1"`
	Issr    *CertificateIssuer1 `xml:"Issr"`
	SrlNb   string              `xml:"SrlNb"`
}

// KEK4 ...
type KEK4 struct {
	XMLName       *xml.Name                  `xml:"KEK4"`
	Vrsn          float64                    `xml:"Vrsn"`
	KEKId         *KEKIdentifier2            `xml:"KEKId"`
	KeyNcrptnAlgo *AlgorithmIdentification13 `xml:"KeyNcrptnAlgo"`
	NcrptdKey     string                     `xml:"NcrptdKey"`
}

// KEKIdentifier2 ...
type KEKIdentifier2 struct {
	XMLName   *xml.Name `xml:"KEKIdentifier2"`
	KeyId     string    `xml:"KeyId"`
	KeyVrsn   string    `xml:"KeyVrsn"`
	SeqNb     float64   `xml:"SeqNb"`
	DerivtnId string    `xml:"DerivtnId"`
}

// KeyTransport4 ...
type KeyTransport4 struct {
	XMLName       *xml.Name                  `xml:"KeyTransport4"`
	Vrsn          float64                    `xml:"Vrsn"`
	RcptId        *Recipient5Choice          `xml:"RcptId"`
	KeyNcrptnAlgo *AlgorithmIdentification11 `xml:"KeyNcrptnAlgo"`
	NcrptdKey     string                     `xml:"NcrptdKey"`
}

// Max10000Binary ...
type Max10000Binary string

// Max100KBinary ...
type Max100KBinary string

// Max10Text ...
type Max10Text string

// Max140Binary ...
type Max140Binary string

// Max140Text ...
type Max140Text string

// Max16Text ...
type Max16Text string

// Max20000Text ...
type Max20000Text string

// Max30Text ...
type Max30Text string

// Max35Binary ...
type Max35Binary string

// Max35Text ...
type Max35Text string

// Max3NumericText ...
type Max3NumericText string

// Max5000Binary ...
type Max5000Binary string

// Max500Binary ...
type Max500Binary string

// Max500Text ...
type Max500Text string

// Max6Text ...
type Max6Text string

// Max70Text ...
type Max70Text string

// MessageFunction6Code ...
type MessageFunction6Code string

// Min2Max3AlphaText ...
type Min2Max3AlphaText string

// Min2Max3NumericText ...
type Min2Max3NumericText string

// Min5Max16Binary ...
type Min5Max16Binary string

// Min6Max8Text ...
type Min6Max8Text string

// Min8Max28NumericText ...
type Min8Max28NumericText string

// NameAndAddress3 ...
type NameAndAddress3 struct {
	XMLName *xml.Name       `xml:"NameAndAddress3"`
	Nm      string          `xml:"Nm"`
	Adr     *PostalAddress1 `xml:"Adr"`
}

// Number ...
type Number float64

// OutputFormat1Code ...
type OutputFormat1Code string

// Parameter4 ...
type Parameter4 struct {
	XMLName      *xml.Name                  `xml:"Parameter4"`
	NcrptnFrmt   string                     `xml:"NcrptnFrmt"`
	DgstAlgo     string                     `xml:"DgstAlgo"`
	MskGnrtrAlgo *AlgorithmIdentification12 `xml:"MskGnrtrAlgo"`
}

// Parameter5 ...
type Parameter5 struct {
	XMLName  *xml.Name `xml:"Parameter5"`
	DgstAlgo string    `xml:"DgstAlgo"`
}

// Parameter6 ...
type Parameter6 struct {
	XMLName      *xml.Name `xml:"Parameter6"`
	NcrptnFrmt   string    `xml:"NcrptnFrmt"`
	InitlstnVctr string    `xml:"InitlstnVctr"`
	BPddg        string    `xml:"BPddg"`
}

// Parameter7 ...
type Parameter7 struct {
	XMLName      *xml.Name `xml:"Parameter7"`
	InitlstnVctr string    `xml:"InitlstnVctr"`
	BPddg        string    `xml:"BPddg"`
}

// PartyIdentification72Choice ...
type PartyIdentification72Choice struct {
	XMLName *xml.Name               `xml:"PartyIdentification72Choice"`
	AnyBIC  string                  `xml:"AnyBIC"`
	PrtryId *GenericIdentification1 `xml:"PrtryId"`
}

// PartyType10Code ...
type PartyType10Code string

// PartyType11Code ...
type PartyType11Code string

// PartyType9Code ...
type PartyType9Code string

// PaymentCard13 ...
type PaymentCard13 struct {
	XMLName        *xml.Name                 `xml:"PaymentCard13"`
	PrtctdCardData *ContentInformationType10 `xml:"PrtctdCardData"`
	PlainCardData  *PlainCardData9           `xml:"PlainCardData"`
	MskdPAN        string                    `xml:"MskdPAN"`
	CardPdctTp     string                    `xml:"CardPdctTp"`
	CardPdctNm     string                    `xml:"CardPdctNm"`
}

// PlainCardData9 ...
type PlainCardData9 struct {
	XMLName   *xml.Name     `xml:"PlainCardData9"`
	PAN       string        `xml:"PAN"`
	CardSeqNb string        `xml:"CardSeqNb"`
	FctvDt    string        `xml:"FctvDt"`
	XpryDt    string        `xml:"XpryDt"`
	SvcCd     string        `xml:"SvcCd"`
	TrckData  []*TrackData1 `xml:"TrckData"`
}

// PlusOrMinusIndicator ...
type PlusOrMinusIndicator bool

// PostalAddress1 ...
type PostalAddress1 struct {
	XMLName     *xml.Name `xml:"PostalAddress1"`
	AdrTp       string    `xml:"AdrTp"`
	AdrLine     []string  `xml:"AdrLine"`
	StrtNm      string    `xml:"StrtNm"`
	BldgNb      string    `xml:"BldgNb"`
	PstCd       string    `xml:"PstCd"`
	TwnNm       string    `xml:"TwnNm"`
	CtrySubDvsn string    `xml:"CtrySubDvsn"`
	Ctry        string    `xml:"Ctry"`
}

// PostalAddress18 ...
type PostalAddress18 struct {
	XMLName     *xml.Name `xml:"PostalAddress18"`
	AdrLine     []string  `xml:"AdrLine"`
	StrtNm      string    `xml:"StrtNm"`
	BldgNb      string    `xml:"BldgNb"`
	PstCd       string    `xml:"PstCd"`
	TwnNm       string    `xml:"TwnNm"`
	CtrySubDvsn []string  `xml:"CtrySubDvsn"`
	Ctry        string    `xml:"Ctry"`
}

// Recipient4Choice ...
type Recipient4Choice struct {
	XMLName    *xml.Name       `xml:"Recipient4Choice"`
	KeyTrnsprt *KeyTransport4  `xml:"KeyTrnsprt"`
	KEK        *KEK4           `xml:"KEK"`
	KeyIdr     *KEKIdentifier2 `xml:"KeyIdr"`
}

// Recipient5Choice ...
type Recipient5Choice struct {
	XMLName      *xml.Name               `xml:"Recipient5Choice"`
	IssrAndSrlNb *IssuerAndSerialNumber1 `xml:"IssrAndSrlNb"`
	KeyIdr       *KEKIdentifier2         `xml:"KeyIdr"`
}

// RelativeDistinguishedName1 ...
type RelativeDistinguishedName1 struct {
	XMLName *xml.Name `xml:"RelativeDistinguishedName1"`
	AttrTp  string    `xml:"AttrTp"`
	AttrVal string    `xml:"AttrVal"`
}

// Response3Code ...
type Response3Code string

// ResponseType2 ...
type ResponseType2 struct {
	XMLName      *xml.Name `xml:"ResponseType2"`
	Rslt         string    `xml:"Rslt"`
	RsltDtls     string    `xml:"RsltDtls"`
	AddtlRsltInf string    `xml:"AddtlRsltInf"`
}

// ResultDetail1Code ...
type ResultDetail1Code string

// Traceability3 ...
type Traceability3 struct {
	XMLName     *xml.Name                `xml:"Traceability3"`
	RlayId      *GenericIdentification74 `xml:"RlayId"`
	TracDtTmIn  string                   `xml:"TracDtTmIn"`
	TracDtTmOut string                   `xml:"TracDtTmOut"`
}

// TrackData1 ...
type TrackData1 struct {
	XMLName *xml.Name `xml:"TrackData1"`
	TrckNb  string    `xml:"TrckNb"`
	TrckVal string    `xml:"TrckVal"`
}

// TransactionIdentifier2 ...
type TransactionIdentifier2 struct {
	XMLName   *xml.Name `xml:"TransactionIdentifier2"`
	RcncltnDt string    `xml:"RcncltnDt"`
	RcncltnId string    `xml:"RcncltnId"`
}

// TransactionVerificationResult4 ...
type TransactionVerificationResult4 struct {
	XMLName    *xml.Name `xml:"TransactionVerificationResult4"`
	Mtd        string    `xml:"Mtd"`
	VrfctnNtty string    `xml:"VrfctnNtty"`
	Rslt       string    `xml:"Rslt"`
	AddtlRslt  string    `xml:"AddtlRslt"`
}

// TypeOfAmount5Code ...
type TypeOfAmount5Code string

// TypeOfAmount6Code ...
type TypeOfAmount6Code string

// TypeOfAmount7Code ...
type TypeOfAmount7Code string

// UPICIdentifier ...
type UPICIdentifier string

// UserInterface3Code ...
type UserInterface3Code string

// UserInterface4Code ...
type UserInterface4Code string

// Verification1Code ...
type Verification1Code string
