// Code generated by xgen. DO NOT EDIT.

package head_001_001_01

import (
	"encoding/xml"
)

// AppHdr ...
type AppHdr *BusinessApplicationHeaderV01

// AddressType2Code ...
type AddressType2Code string

// AnyBICIdentifier ...
type AnyBICIdentifier string

// BICFIIdentifier ...
type BICFIIdentifier string

// BranchAndFinancialInstitutionIdentification5 ...
type BranchAndFinancialInstitutionIdentification5 struct {
	XMLName    *xml.Name                            `xml:"urn1:BranchAndFinancialInstitutionIdentification5"`
	FinInstnId *FinancialInstitutionIdentification8 `xml:"urn1:FinInstnId"`
	BrnchId    *BranchData2                         `xml:"urn1:BrnchId"`
}

// BranchData2 ...
type BranchData2 struct {
	XMLName *xml.Name       `xml:"urn1:BranchData2"`
	Id      string          `xml:"urn1:Id"`
	Nm      string          `xml:"urn1:Nm"`
	PstlAdr *PostalAddress6 `xml:"urn1:PstlAdr"`
}

// BusinessApplicationHeader1 ...
type BusinessApplicationHeader1 struct {
	XMLName    *xml.Name          `xml:"urn1:BusinessApplicationHeader1"`
	CharSet    string             `xml:"urn1:CharSet"`
	Fr         *Party9Choice      `xml:"urn1:Fr"`
	To         *Party9Choice      `xml:"urn1:To"`
	BizMsgIdr  string             `xml:"urn1:BizMsgIdr"`
	MsgDefIdr  string             `xml:"urn1:MsgDefIdr"`
	BizSvc     string             `xml:"urn1:BizSvc"`
	CreDt      string             `xml:"urn1:CreDt"`
	CpyDplct   string             `xml:"urn1:CpyDplct"`
	PssblDplct bool               `xml:"urn1:PssblDplct"`
	Prty       string             `xml:"urn1:Prty"`
	Sgntr      *SignatureEnvelope `xml:"urn1:Sgntr"`
}

// BusinessApplicationHeaderV01 ...
type BusinessApplicationHeaderV01 struct {
	XMLName    *xml.Name                   `xml:"urn1:BusinessApplicationHeaderV01"`
	CharSet    string                      `xml:"urn1:CharSet"`
	Fr         *Party9Choice               `xml:"urn1:Fr"`
	To         *Party9Choice               `xml:"urn1:To"`
	BizMsgIdr  string                      `xml:"urn1:BizMsgIdr"`
	MsgDefIdr  string                      `xml:"urn1:MsgDefIdr"`
	BizSvc     string                      `xml:"urn1:BizSvc"`
	CreDt      string                      `xml:"urn1:CreDt"`
	CpyDplct   string                      `xml:"urn1:CpyDplct"`
	PssblDplct bool                        `xml:"urn1:PssblDplct"`
	Prty       string                      `xml:"urn1:Prty"`
	Sgntr      *SignatureEnvelope          `xml:"urn1:Sgntr"`
	Rltd       *BusinessApplicationHeader1 `xml:"urn1:Rltd"`
}

// BusinessMessagePriorityCode ...
type BusinessMessagePriorityCode string

// ClearingSystemIdentification2Choice ...
type ClearingSystemIdentification2Choice struct {
	XMLName *xml.Name `xml:"urn1:ClearingSystemIdentification2Choice"`
	Cd      string    `xml:"urn1:Cd"`
	Prtry   string    `xml:"urn1:Prtry"`
}

// ClearingSystemMemberIdentification2 ...
type ClearingSystemMemberIdentification2 struct {
	XMLName  *xml.Name                            `xml:"urn1:ClearingSystemMemberIdentification2"`
	ClrSysId *ClearingSystemIdentification2Choice `xml:"urn1:ClrSysId"`
	MmbId    string                               `xml:"urn1:MmbId"`
}

// ContactDetails2 ...
type ContactDetails2 struct {
	XMLName  *xml.Name `xml:"urn1:ContactDetails2"`
	NmPrfx   string    `xml:"urn1:NmPrfx"`
	Nm       string    `xml:"urn1:Nm"`
	PhneNb   string    `xml:"urn1:PhneNb"`
	MobNb    string    `xml:"urn1:MobNb"`
	FaxNb    string    `xml:"urn1:FaxNb"`
	EmailAdr string    `xml:"urn1:EmailAdr"`
	Othr     string    `xml:"urn1:Othr"`
}

// CopyDuplicate1Code ...
type CopyDuplicate1Code string

// CountryCode ...
type CountryCode string

// DateAndPlaceOfBirth ...
type DateAndPlaceOfBirth struct {
	XMLName     *xml.Name `xml:"urn1:DateAndPlaceOfBirth"`
	BirthDt     string    `xml:"urn1:BirthDt"`
	PrvcOfBirth string    `xml:"urn1:PrvcOfBirth"`
	CityOfBirth string    `xml:"urn1:CityOfBirth"`
	CtryOfBirth string    `xml:"urn1:CtryOfBirth"`
}

// ExternalClearingSystemIdentification1Code ...
type ExternalClearingSystemIdentification1Code string

// ExternalFinancialInstitutionIdentification1Code ...
type ExternalFinancialInstitutionIdentification1Code string

// ExternalOrganisationIdentification1Code ...
type ExternalOrganisationIdentification1Code string

// ExternalPersonIdentification1Code ...
type ExternalPersonIdentification1Code string

// FinancialIdentificationSchemeName1Choice ...
type FinancialIdentificationSchemeName1Choice struct {
	XMLName *xml.Name `xml:"urn1:FinancialIdentificationSchemeName1Choice"`
	Cd      string    `xml:"urn1:Cd"`
	Prtry   string    `xml:"urn1:Prtry"`
}

// FinancialInstitutionIdentification8 ...
type FinancialInstitutionIdentification8 struct {
	XMLName     *xml.Name                            `xml:"urn1:FinancialInstitutionIdentification8"`
	BICFI       string                               `xml:"urn1:BICFI"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"urn1:ClrSysMmbId"`
	Nm          string                               `xml:"urn1:Nm"`
	PstlAdr     *PostalAddress6                      `xml:"urn1:PstlAdr"`
	Othr        *GenericFinancialIdentification1     `xml:"urn1:Othr"`
}

// GenericFinancialIdentification1 ...
type GenericFinancialIdentification1 struct {
	XMLName *xml.Name                                 `xml:"urn1:GenericFinancialIdentification1"`
	Id      string                                    `xml:"urn1:Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"urn1:SchmeNm"`
	Issr    string                                    `xml:"urn1:Issr"`
}

// GenericOrganisationIdentification1 ...
type GenericOrganisationIdentification1 struct {
	XMLName *xml.Name                                    `xml:"urn1:GenericOrganisationIdentification1"`
	Id      string                                       `xml:"urn1:Id"`
	SchmeNm *OrganisationIdentificationSchemeName1Choice `xml:"urn1:SchmeNm"`
	Issr    string                                       `xml:"urn1:Issr"`
}

// GenericPersonIdentification1 ...
type GenericPersonIdentification1 struct {
	XMLName *xml.Name                              `xml:"urn1:GenericPersonIdentification1"`
	Id      string                                 `xml:"urn1:Id"`
	SchmeNm *PersonIdentificationSchemeName1Choice `xml:"urn1:SchmeNm"`
	Issr    string                                 `xml:"urn1:Issr"`
}

// ISODate ...
type ISODate string

// ISONormalisedDateTime ...
type ISONormalisedDateTime string

// Max140Text ...
type Max140Text string

// Max16Text ...
type Max16Text string

// Max2048Text ...
type Max2048Text string

// Max35Text ...
type Max35Text string

// Max70Text ...
type Max70Text string

// NamePrefix1Code ...
type NamePrefix1Code string

// OrganisationIdentification7 ...
type OrganisationIdentification7 struct {
	XMLName *xml.Name                             `xml:"urn1:OrganisationIdentification7"`
	AnyBIC  string                                `xml:"urn1:AnyBIC"`
	Othr    []*GenericOrganisationIdentification1 `xml:"urn1:Othr"`
}

// OrganisationIdentificationSchemeName1Choice ...
type OrganisationIdentificationSchemeName1Choice struct {
	XMLName *xml.Name `xml:"urn1:OrganisationIdentificationSchemeName1Choice"`
	Cd      string    `xml:"urn1:Cd"`
	Prtry   string    `xml:"urn1:Prtry"`
}

// Party10Choice ...
type Party10Choice struct {
	XMLName *xml.Name                    `xml:"urn1:Party10Choice"`
	OrgId   *OrganisationIdentification7 `xml:"urn1:OrgId"`
	PrvtId  *PersonIdentification5       `xml:"urn1:PrvtId"`
}

// Party9Choice ...
type Party9Choice struct {
	XMLName *xml.Name                                     `xml:"urn1:Party9Choice"`
	OrgId   *PartyIdentification42                        `xml:"urn1:OrgId"`
	FIId    *BranchAndFinancialInstitutionIdentification5 `xml:"urn1:FIId"`
}

// PartyIdentification42 ...
type PartyIdentification42 struct {
	XMLName   *xml.Name        `xml:"urn1:PartyIdentification42"`
	Nm        string           `xml:"urn1:Nm"`
	PstlAdr   *PostalAddress6  `xml:"urn1:PstlAdr"`
	Id        *Party10Choice   `xml:"urn1:Id"`
	CtryOfRes string           `xml:"urn1:CtryOfRes"`
	CtctDtls  *ContactDetails2 `xml:"urn1:CtctDtls"`
}

// PersonIdentification5 ...
type PersonIdentification5 struct {
	XMLName         *xml.Name                       `xml:"urn1:PersonIdentification5"`
	DtAndPlcOfBirth *DateAndPlaceOfBirth            `xml:"urn1:DtAndPlcOfBirth"`
	Othr            []*GenericPersonIdentification1 `xml:"urn1:Othr"`
}

// PersonIdentificationSchemeName1Choice ...
type PersonIdentificationSchemeName1Choice struct {
	XMLName *xml.Name `xml:"urn1:PersonIdentificationSchemeName1Choice"`
	Cd      string    `xml:"urn1:Cd"`
	Prtry   string    `xml:"urn1:Prtry"`
}

// PhoneNumber ...
type PhoneNumber string

// PostalAddress6 ...
type PostalAddress6 struct {
	XMLName     *xml.Name `xml:"urn1:PostalAddress6"`
	AdrTp       string    `xml:"urn1:AdrTp"`
	Dept        string    `xml:"urn1:Dept"`
	SubDept     string    `xml:"urn1:SubDept"`
	StrtNm      string    `xml:"urn1:StrtNm"`
	BldgNb      string    `xml:"urn1:BldgNb"`
	PstCd       string    `xml:"urn1:PstCd"`
	TwnNm       string    `xml:"urn1:TwnNm"`
	CtrySubDvsn string    `xml:"urn1:CtrySubDvsn"`
	Ctry        string    `xml:"urn1:Ctry"`
	AdrLine     []string  `xml:"urn1:AdrLine"`
}

// SignatureEnvelope ...
type SignatureEnvelope struct {
	XMLName *xml.Name `xml:"urn1:SignatureEnvelope"`
}

// UnicodeChartsCode ...
type UnicodeChartsCode string

// YesNoIndicator ...
type YesNoIndicator bool
