// Code generated by xgen. DO NOT EDIT.

package cain_003_001_01

// Document ...
type Document *Document

// AccountChoiceMethod1Code ...
type AccountChoiceMethod1Code string

// AccountIdentification30Choice ...
type AccountIdentification30Choice struct {
	Card   string `json:"Card"`
	MSISDN string `json:"MSISDN"`
	EMail  string `json:"EMail"`
	IBAN   string `json:"IBAN"`
	BBAN   string `json:"BBAN"`
	UPIC   string `json:"UPIC"`
	Dmst   string `json:"Dmst"`
	Othr   string `json:"Othr"`
}

// Acquirer6 ...
type Acquirer6 struct {
	Id     string `json:"Id"`
	Issr   string `json:"Issr"`
	CtryCd string `json:"CtryCd"`
}

// AcquirerFinancialInitiation ...
type AcquirerFinancialInitiation struct {
	Hdr      *Header17                     `json:"Hdr"`
	FinInitn *AcquirerFinancialInitiation1 `json:"FinInitn"`
	SctyTrlr *ContentInformationType15     `json:"SctyTrlr"`
}

// AcquirerFinancialInitiation1 ...
type AcquirerFinancialInitiation1 struct {
	Envt  *CardTransactionEnvironment1 `json:"Envt"`
	Cntxt *CardTransactionContext1     `json:"Cntxt"`
	Tx    *CardTransaction5            `json:"Tx"`
}

// ActionMessage3 ...
type ActionMessage3 struct {
	Dstn string `json:"Dstn"`
	Frmt string `json:"Frmt"`
	Cntt string `json:"Cntt"`
}

// ActionType4Code ...
type ActionType4Code string

// AddressType2Code ...
type AddressType2Code string

// AddressVerification1 ...
type AddressVerification1 struct {
	AdrDgts    string `json:"AdrDgts"`
	PstlCdDgts string `json:"PstlCdDgts"`
}

// Algorithm11Code ...
type Algorithm11Code string

// Algorithm12Code ...
type Algorithm12Code string

// Algorithm13Code ...
type Algorithm13Code string

// Algorithm15Code ...
type Algorithm15Code string

// Algorithm7Code ...
type Algorithm7Code string

// Algorithm8Code ...
type Algorithm8Code string

// AlgorithmIdentification11 ...
type AlgorithmIdentification11 struct {
	Algo  string      `json:"Algo"`
	Param *Parameter4 `json:"Param"`
}

// AlgorithmIdentification12 ...
type AlgorithmIdentification12 struct {
	Algo  string      `json:"Algo"`
	Param *Parameter5 `json:"Param"`
}

// AlgorithmIdentification13 ...
type AlgorithmIdentification13 struct {
	Algo  string      `json:"Algo"`
	Param *Parameter6 `json:"Param"`
}

// AlgorithmIdentification14 ...
type AlgorithmIdentification14 struct {
	Algo  string      `json:"Algo"`
	Param *Parameter6 `json:"Param"`
}

// AlgorithmIdentification15 ...
type AlgorithmIdentification15 struct {
	Algo  string      `json:"Algo"`
	Param *Parameter7 `json:"Param"`
}

// AmountAndDirection41 ...
type AmountAndDirection41 struct {
	Amt *CurrencyAndAmount `json:"Amt"`
	Sgn bool               `json:"Sgn"`
}

// AntiMoneyLaundering1 ...
type AntiMoneyLaundering1 struct {
	SndrNm              string               `json:"SndrNm"`
	SndrAdr             *PostalAddress18     `json:"SndrAdr"`
	SndrNtlIdr          string               `json:"SndrNtlIdr"`
	NtlIdrCtry          string               `json:"NtlIdrCtry"`
	SndrPsptNb          string               `json:"SndrPsptNb"`
	PsptIssgCtry        string               `json:"PsptIssgCtry"`
	SndrTaxIdr          string               `json:"SndrTaxIdr"`
	TaxCtry             string               `json:"TaxCtry"`
	SndrCstmrIdr        string               `json:"SndrCstmrIdr"`
	SndrDtAndPlcOfBirth *DateAndPlaceOfBirth `json:"SndrDtAndPlcOfBirth"`
	RcvrNm              string               `json:"RcvrNm"`
	TxRef               string               `json:"TxRef"`
}

// AnyBICIdentifier ...
type AnyBICIdentifier string

// AttendanceContext1Code ...
type AttendanceContext1Code string

// AttributeType1Code ...
type AttributeType1Code string

// AuthenticatedData4 ...
type AuthenticatedData4 struct {
	Vrsn        float64                    `json:"Vrsn"`
	Rcpt        []*Recipient4Choice        `json:"Rcpt"`
	MACAlgo     *AlgorithmIdentification15 `json:"MACAlgo"`
	NcpsltdCntt *EncapsulatedContent3      `json:"NcpsltdCntt"`
	MAC         string                     `json:"MAC"`
}

// AuthenticationEntity2Code ...
type AuthenticationEntity2Code string

// AuthenticationMethod5Code ...
type AuthenticationMethod5Code string

// AuthenticationMethod6Code ...
type AuthenticationMethod6Code string

// AuthorisationResult7 ...
type AuthorisationResult7 struct {
	AuthstnNtty *GenericIdentification75 `json:"AuthstnNtty"`
	TxRspn      *ResponseType2           `json:"TxRspn"`
	AuthstnCd   string                   `json:"AuthstnCd"`
	AddtlInf    []*ActionMessage3        `json:"AddtlInf"`
}

// BBANIdentifier ...
type BBANIdentifier string

// BaseOneRate ...
type BaseOneRate float64

// BytePadding1Code ...
type BytePadding1Code string

// CardAcceptorTerminal1 ...
type CardAcceptorTerminal1 struct {
	Id       *GenericIdentification32         `json:"Id"`
	Lctn     *PostalAddress18                 `json:"Lctn"`
	Cpblties *PointOfInteractionCapabilities4 `json:"Cpblties"`
}

// CardAccount1 ...
type CardAccount1 struct {
	SelctnMtd    string                         `json:"SelctnMtd"`
	SelctdAcctTp string                         `json:"SelctdAcctTp"`
	AcctNm       string                         `json:"AcctNm"`
	AcctOwnr     *NameAndAddress3               `json:"AcctOwnr"`
	AcctIdr      *AccountIdentification30Choice `json:"AcctIdr"`
	Svcr         *PartyIdentification72Choice   `json:"Svcr"`
}

// CardAccountType2Code ...
type CardAccountType2Code string

// CardDataReading2Code ...
type CardDataReading2Code string

// CardDataReading3Code ...
type CardDataReading3Code string

// CardFallback1Code ...
type CardFallback1Code string

// CardPaymentServiceType3Code ...
type CardPaymentServiceType3Code string

// CardPaymentServiceType7Code ...
type CardPaymentServiceType7Code string

// CardPaymentServiceType8Code ...
type CardPaymentServiceType8Code string

// CardPaymentToken4 ...
type CardPaymentToken4 struct {
	Tkn           string                    `json:"Tkn"`
	CardSeqNb     string                    `json:"CardSeqNb"`
	TknXpryDt     string                    `json:"TknXpryDt"`
	TknChrtc      []string                  `json:"TknChrtc"`
	TknRqstr      *PaymentTokenIdentifiers1 `json:"TknRqstr"`
	TknAssrncLvl  float64                   `json:"TknAssrncLvl"`
	TknAssrncData string                    `json:"TknAssrncData"`
}

// CardTransaction3 ...
type CardTransaction3 struct {
	AccptrTxDtTm string `json:"AccptrTxDtTm"`
	InitrTxId    string `json:"InitrTxId"`
	InitrId      string `json:"InitrId"`
}

// CardTransaction5 ...
type CardTransaction5 struct {
	TxTp              string                  `json:"TxTp"`
	AddtlSvc          []string                `json:"AddtlSvc"`
	SvcAttr           string                  `json:"SvcAttr"`
	MrchntCtgyCd      string                  `json:"MrchntCtgyCd"`
	Rcncltn           *TransactionIdentifier2 `json:"Rcncltn"`
	AccptrTxDtTm      string                  `json:"AccptrTxDtTm"`
	AccptrTxId        string                  `json:"AccptrTxId"`
	InitrTxId         string                  `json:"InitrTxId"`
	TxLifeCyclId      string                  `json:"TxLifeCyclId"`
	TxLifeCyclSeqNb   float64                 `json:"TxLifeCyclSeqNb"`
	TxLifeCyclSeqCntr float64                 `json:"TxLifeCyclSeqCntr"`
	AcqrrTxRef        string                  `json:"AcqrrTxRef"`
	CardIssrRefData   string                  `json:"CardIssrRefData"`
	OrgnlTx           *CardTransaction3       `json:"OrgnlTx"`
	TxDtls            *CardTransactionDetail3 `json:"TxDtls"`
	AuthstnRslt       *AuthorisationResult7   `json:"AuthstnRslt"`
}

// CardTransactionAmount3 ...
type CardTransactionAmount3 struct {
	TtlAmt           *CurrencyAndAmount `json:"TtlAmt"`
	AmtQlfr          string             `json:"AmtQlfr"`
	CrdhldrBllgTxAmt *DetailedAmount8   `json:"CrdhldrBllgTxAmt"`
	RcncltnTxAmt     *DetailedAmount8   `json:"RcncltnTxAmt"`
	DtldAmt          []*DetailedAmount9 `json:"DtldAmt"`
}

// CardTransactionCondition1 ...
type CardTransactionCondition1 struct {
	Prgm string `json:"Prgm"`
	Val  string `json:"Val"`
}

// CardTransactionContext1 ...
type CardTransactionContext1 struct {
	TxCntxt   *CardTransactionContext2 `json:"TxCntxt"`
	SaleCntxt *SaleContext1            `json:"SaleCntxt"`
}

// CardTransactionContext2 ...
type CardTransactionContext2 struct {
	CardPres       bool                             `json:"CardPres"`
	CrdhldrPres    bool                             `json:"CrdhldrPres"`
	LctnCtgy       string                           `json:"LctnCtgy"`
	AttndncCntxt   string                           `json:"AttndncCntxt"`
	TxEnvt         string                           `json:"TxEnvt"`
	HstgCtgy       string                           `json:"HstgCtgy"`
	TxChanl        string                           `json:"TxChanl"`
	CardDataNtryMd string                           `json:"CardDataNtryMd"`
	FllbckInd      string                           `json:"FllbckInd"`
	SpprtdOptn     []string                         `json:"SpprtdOptn"`
	SpclConds      []*CardTransactionCondition1     `json:"SpclConds"`
	RskInd         []*CardTransactionRiskIndicator1 `json:"RskInd"`
}

// CardTransactionDetail3 ...
type CardTransactionDetail3 struct {
	TxAmts         *CardTransactionAmount3 `json:"TxAmts"`
	TxFees         []*DetailedAmount11     `json:"TxFees"`
	AddtlAmts      []*DetailedAmount10     `json:"AddtlAmts"`
	MsgRsn         string                  `json:"MsgRsn"`
	VldtyDt        string                  `json:"VldtyDt"`
	UattnddLvlCtgy string                  `json:"UattnddLvlCtgy"`
	AcctFr         *CardAccount1           `json:"AcctFr"`
	AcctTo         *CardAccount1           `json:"AcctTo"`
	Instlmt        *RecurringTransaction2  `json:"Instlmt"`
	AML            *AntiMoneyLaundering1   `json:"AML"`
	ICCRltdData    string                  `json:"ICCRltdData"`
}

// CardTransactionEnvironment1 ...
type CardTransactionEnvironment1 struct {
	Acqrr             *Acquirer6                `json:"Acqrr"`
	CardSchmeId       string                    `json:"CardSchmeId"`
	Accptr            *Organisation18           `json:"Accptr"`
	Termnl            *CardAcceptorTerminal1    `json:"Termnl"`
	Card              *PaymentCard12            `json:"Card"`
	CstmrDvc          *CustomerDevice1          `json:"CstmrDvc"`
	Wllt              *CustomerDevice1          `json:"Wllt"`
	PmtTkn            *CardPaymentToken4        `json:"PmtTkn"`
	Crdhldr           *Cardholder9              `json:"Crdhldr"`
	PrtctdCrdhldrData *ContentInformationType10 `json:"PrtctdCrdhldrData"`
}

// CardTransactionRiskIndicator1 ...
type CardTransactionRiskIndicator1 struct {
	Rsn         []string `json:"Rsn"`
	Lvl         float64  `json:"Lvl"`
	RcmmnddActn []string `json:"RcmmnddActn"`
}

// CardTransactionRiskReason1Code ...
type CardTransactionRiskReason1Code string

// Cardholder9 ...
type Cardholder9 struct {
	Id           *PersonIdentification7            `json:"Id"`
	Nm           string                            `json:"Nm"`
	Lang         string                            `json:"Lang"`
	BllgAdr      *PostalAddress18                  `json:"BllgAdr"`
	ShppgAdr     *PostalAddress18                  `json:"ShppgAdr"`
	Authntcn     []*CardholderAuthentication7      `json:"Authntcn"`
	TxVrfctnRslt []*TransactionVerificationResult4 `json:"TxVrfctnRslt"`
	PrsnlData    string                            `json:"PrsnlData"`
}

// CardholderAuthentication7 ...
type CardholderAuthentication7 struct {
	AuthntcnMtd       string                    `json:"AuthntcnMtd"`
	AuthntcnVal       string                    `json:"AuthntcnVal"`
	PrtctdAuthntcnVal *ContentInformationType10 `json:"PrtctdAuthntcnVal"`
	CrdhldrOnLinePIN  *OnLinePIN4               `json:"CrdhldrOnLinePIN"`
	CrdhldrId         *PersonIdentification7    `json:"CrdhldrId"`
	AdrVrfctn         *AddressVerification1     `json:"AdrVrfctn"`
}

// CardholderVerificationCapability2Code ...
type CardholderVerificationCapability2Code string

// CertificateIssuer1 ...
type CertificateIssuer1 struct {
	RltvDstngshdNm []*RelativeDistinguishedName1 `json:"RltvDstngshdNm"`
}

// CommunicationAddress5 ...
type CommunicationAddress5 struct {
	PstlAdr      *PostalAddress18 `json:"PstlAdr"`
	Email        string           `json:"Email"`
	URLAdr       string           `json:"URLAdr"`
	Phne         string           `json:"Phne"`
	CstmrSvc     string           `json:"CstmrSvc"`
	AddtlCtctInf string           `json:"AddtlCtctInf"`
}

// ContentInformationType10 ...
type ContentInformationType10 struct {
	CnttTp     string          `json:"CnttTp"`
	EnvlpdData *EnvelopedData4 `json:"EnvlpdData"`
}

// ContentInformationType15 ...
type ContentInformationType15 struct {
	CnttTp       string              `json:"CnttTp"`
	AuthntcdData *AuthenticatedData4 `json:"AuthntcdData"`
}

// ContentType2Code ...
type ContentType2Code string

// CountryCode ...
type CountryCode string

// CurrencyAndAmountSimpleType ...
type CurrencyAndAmountSimpleType float64

// CurrencyAndAmount ...
type CurrencyAndAmount struct {
	CcyAttr string  `json:"-,omitempty", bson:"-,omitempty", xml:"Ccy,attr"`
	Value   float64 `json:"float64"`
}

// CurrencyCode ...
type CurrencyCode string

// CustomerDevice1 ...
type CustomerDevice1 struct {
	Id    string `json:"Id"`
	Tp    string `json:"Tp"`
	Prvdr string `json:"Prvdr"`
}

// DateAndPlaceOfBirth ...
type DateAndPlaceOfBirth struct {
	BirthDt     string `json:"BirthDt"`
	PrvcOfBirth string `json:"PrvcOfBirth"`
	CityOfBirth string `json:"CityOfBirth"`
	CtryOfBirth string `json:"CtryOfBirth"`
}

// DetailedAmount10 ...
type DetailedAmount10 struct {
	Tp      string             `json:"Tp"`
	AddtlTp string             `json:"AddtlTp"`
	Amt     *CurrencyAndAmount `json:"Amt"`
	Labl    string             `json:"Labl"`
}

// DetailedAmount11 ...
type DetailedAmount11 struct {
	Tp       string                `json:"Tp"`
	AddtlTp  string                `json:"AddtlTp"`
	Amt      *AmountAndDirection41 `json:"Amt"`
	OrgnlAmt *AmountAndDirection41 `json:"OrgnlAmt"`
}

// DetailedAmount8 ...
type DetailedAmount8 struct {
	Amt      float64 `json:"Amt"`
	XchgRate float64 `json:"XchgRate"`
	QtnDt    string  `json:"QtnDt"`
	Labl     string  `json:"Labl"`
}

// DetailedAmount9 ...
type DetailedAmount9 struct {
	Tp      string  `json:"Tp"`
	AddtlTp string  `json:"AddtlTp"`
	Amt     float64 `json:"Amt"`
	Labl    string  `json:"Labl"`
}

// DisplayCapabilities3 ...
type DisplayCapabilities3 struct {
	Dstn      string   `json:"Dstn"`
	AvlblFrmt []string `json:"AvlblFrmt"`
	NbOfLines float64  `json:"NbOfLines"`
	LineWidth float64  `json:"LineWidth"`
	AvlblLang []string `json:"AvlblLang"`
}

// EncapsulatedContent3 ...
type EncapsulatedContent3 struct {
	CnttTp string `json:"CnttTp"`
	Cntt   string `json:"Cntt"`
}

// EncryptedContent3 ...
type EncryptedContent3 struct {
	CnttTp         string                     `json:"CnttTp"`
	CnttNcrptnAlgo *AlgorithmIdentification14 `json:"CnttNcrptnAlgo"`
	NcrptdData     string                     `json:"NcrptdData"`
}

// EncryptionFormat1Code ...
type EncryptionFormat1Code string

// EnvelopedData4 ...
type EnvelopedData4 struct {
	Vrsn       float64             `json:"Vrsn"`
	Rcpt       []*Recipient4Choice `json:"Rcpt"`
	NcrptdCntt *EncryptedContent3  `json:"NcrptdCntt"`
}

// Exact1NumericText ...
type Exact1NumericText string

// Exact3AlphaNumericText ...
type Exact3AlphaNumericText string

// Exact3NumericText ...
type Exact3NumericText string

// Frequency3Code ...
type Frequency3Code string

// GenericIdentification1 ...
type GenericIdentification1 struct {
	Id      string `json:"Id"`
	SchmeNm string `json:"SchmeNm"`
	Issr    string `json:"Issr"`
}

// GenericIdentification32 ...
type GenericIdentification32 struct {
	Id     string `json:"Id"`
	Tp     string `json:"Tp"`
	Issr   string `json:"Issr"`
	ShrtNm string `json:"ShrtNm"`
}

// GenericIdentification4 ...
type GenericIdentification4 struct {
	Id   string `json:"Id"`
	IdTp string `json:"IdTp"`
}

// GenericIdentification73 ...
type GenericIdentification73 struct {
	Id     string `json:"Id"`
	Tp     string `json:"Tp"`
	Issr   string `json:"Issr"`
	Ctry   string `json:"Ctry"`
	ShrtNm string `json:"ShrtNm"`
}

// GenericIdentification74 ...
type GenericIdentification74 struct {
	Id     string `json:"Id"`
	Tp     string `json:"Tp"`
	Issr   string `json:"Issr"`
	Ctry   string `json:"Ctry"`
	ShrtNm string `json:"ShrtNm"`
}

// GenericIdentification75 ...
type GenericIdentification75 struct {
	Id     string `json:"Id"`
	Tp     string `json:"Tp"`
	Issr   string `json:"Issr"`
	Ctry   string `json:"Ctry"`
	ShrtNm string `json:"ShrtNm"`
}

// Header17 ...
type Header17 struct {
	MsgFctn        string                   `json:"MsgFctn"`
	PrtcolVrsn     string                   `json:"PrtcolVrsn"`
	XchgId         string                   `json:"XchgId"`
	ReTrnsmssnCntr string                   `json:"ReTrnsmssnCntr"`
	CreDtTm        string                   `json:"CreDtTm"`
	InitgPty       *GenericIdentification73 `json:"InitgPty"`
	RcptPty        *GenericIdentification73 `json:"RcptPty"`
	Tracblt        []*Traceability3         `json:"Tracblt"`
}

// IBANIdentifier ...
type IBANIdentifier string

// ISO3NumericCountryCode ...
type ISO3NumericCountryCode string

// ISODate ...
type ISODate string

// ISODateTime ...
type ISODateTime string

// ImpliedCurrencyAndAmount ...
type ImpliedCurrencyAndAmount float64

// InstalmentPlan1Code ...
type InstalmentPlan1Code string

// IssuerAndSerialNumber1 ...
type IssuerAndSerialNumber1 struct {
	Issr  *CertificateIssuer1 `json:"Issr"`
	SrlNb string              `json:"SrlNb"`
}

// KEK4 ...
type KEK4 struct {
	Vrsn          float64                    `json:"Vrsn"`
	KEKId         *KEKIdentifier2            `json:"KEKId"`
	KeyNcrptnAlgo *AlgorithmIdentification13 `json:"KeyNcrptnAlgo"`
	NcrptdKey     string                     `json:"NcrptdKey"`
}

// KEKIdentifier2 ...
type KEKIdentifier2 struct {
	KeyId     string  `json:"KeyId"`
	KeyVrsn   string  `json:"KeyVrsn"`
	SeqNb     float64 `json:"SeqNb"`
	DerivtnId string  `json:"DerivtnId"`
}

// KeyTransport4 ...
type KeyTransport4 struct {
	Vrsn          float64                    `json:"Vrsn"`
	RcptId        *Recipient5Choice          `json:"RcptId"`
	KeyNcrptnAlgo *AlgorithmIdentification11 `json:"KeyNcrptnAlgo"`
	NcrptdKey     string                     `json:"NcrptdKey"`
}

// LanguageCode ...
type LanguageCode string

// LocationCategory2Code ...
type LocationCategory2Code string

// Max10000Binary ...
type Max10000Binary string

// Max100KBinary ...
type Max100KBinary string

// Max10Text ...
type Max10Text string

// Max140Binary ...
type Max140Binary string

// Max140Text ...
type Max140Text string

// Max15NumericText ...
type Max15NumericText string

// Max16Text ...
type Max16Text string

// Max20000Text ...
type Max20000Text string

// Max256Text ...
type Max256Text string

// Max2NumericText ...
type Max2NumericText string

// Max35Binary ...
type Max35Binary string

// Max35NumericText ...
type Max35NumericText string

// Max35Text ...
type Max35Text string

// Max3NumericText ...
type Max3NumericText string

// Max3Text ...
type Max3Text string

// Max45Text ...
type Max45Text string

// Max5000Binary ...
type Max5000Binary string

// Max500Binary ...
type Max500Binary string

// Max500Text ...
type Max500Text string

// Max5NumericText ...
type Max5NumericText string

// Max6Text ...
type Max6Text string

// Max70Text ...
type Max70Text string

// MessageFunction6Code ...
type MessageFunction6Code string

// MessageReason1Code ...
type MessageReason1Code string

// Min2Max3AlphaText ...
type Min2Max3AlphaText string

// Min2Max3NumericText ...
type Min2Max3NumericText string

// Min3Max4NumericText ...
type Min3Max4NumericText string

// Min5Max16Binary ...
type Min5Max16Binary string

// Min6Max8Text ...
type Min6Max8Text string

// Min8Max28NumericText ...
type Min8Max28NumericText string

// NameAndAddress3 ...
type NameAndAddress3 struct {
	Nm  string          `json:"Nm"`
	Adr *PostalAddress1 `json:"Adr"`
}

// Number ...
type Number float64

// OnLineCapability1Code ...
type OnLineCapability1Code string

// OnLinePIN4 ...
type OnLinePIN4 struct {
	NcrptdPINBlck *ContentInformationType10 `json:"NcrptdPINBlck"`
	PINFrmt       string                    `json:"PINFrmt"`
	AddtlInpt     string                    `json:"AddtlInpt"`
}

// Organisation18 ...
type Organisation18 struct {
	Id         *GenericIdentification32 `json:"Id"`
	CmonNm     string                   `json:"CmonNm"`
	Lctn       *CommunicationAddress5   `json:"Lctn"`
	SelctdLang string                   `json:"SelctdLang"`
	SchmeData  string                   `json:"SchmeData"`
}

// OutputFormat1Code ...
type OutputFormat1Code string

// PINFormat3Code ...
type PINFormat3Code string

// Parameter4 ...
type Parameter4 struct {
	NcrptnFrmt   string                     `json:"NcrptnFrmt"`
	DgstAlgo     string                     `json:"DgstAlgo"`
	MskGnrtrAlgo *AlgorithmIdentification12 `json:"MskGnrtrAlgo"`
}

// Parameter5 ...
type Parameter5 struct {
	DgstAlgo string `json:"DgstAlgo"`
}

// Parameter6 ...
type Parameter6 struct {
	NcrptnFrmt   string `json:"NcrptnFrmt"`
	InitlstnVctr string `json:"InitlstnVctr"`
	BPddg        string `json:"BPddg"`
}

// Parameter7 ...
type Parameter7 struct {
	InitlstnVctr string `json:"InitlstnVctr"`
	BPddg        string `json:"BPddg"`
}

// PartyIdentification72Choice ...
type PartyIdentification72Choice struct {
	AnyBIC  string                  `json:"AnyBIC"`
	PrtryId *GenericIdentification1 `json:"PrtryId"`
}

// PartyType10Code ...
type PartyType10Code string

// PartyType11Code ...
type PartyType11Code string

// PartyType3Code ...
type PartyType3Code string

// PartyType4Code ...
type PartyType4Code string

// PartyType9Code ...
type PartyType9Code string

// PaymentCard12 ...
type PaymentCard12 struct {
	PrtctdCardData *ContentInformationType10 `json:"PrtctdCardData"`
	PlainCardData  *PlainCardData10          `json:"PlainCardData"`
	IssrBIN        string                    `json:"IssrBIN"`
	CardCtryCd     string                    `json:"CardCtryCd"`
	CardCcyCd      string                    `json:"CardCcyCd"`
	AddtlCardData  string                    `json:"AddtlCardData"`
}

// PaymentTokenIdentifiers1 ...
type PaymentTokenIdentifiers1 struct {
	PrvdrId string `json:"PrvdrId"`
	RqstrId string `json:"RqstrId"`
}

// PersonIdentification7 ...
type PersonIdentification7 struct {
	DrvrsLicNb      string                    `json:"DrvrsLicNb"`
	CstmrNb         string                    `json:"CstmrNb"`
	SclSctyNb       string                    `json:"SclSctyNb"`
	AlnRegnNb       string                    `json:"AlnRegnNb"`
	PsptNb          string                    `json:"PsptNb"`
	TaxIdNb         string                    `json:"TaxIdNb"`
	IdntyCardNb     string                    `json:"IdntyCardNb"`
	MplyrIdNb       string                    `json:"MplyrIdNb"`
	MplyeeIdNb      string                    `json:"MplyeeIdNb"`
	EmailAdr        string                    `json:"EmailAdr"`
	DtAndPlcOfBirth *DateAndPlaceOfBirth      `json:"DtAndPlcOfBirth"`
	Othr            []*GenericIdentification4 `json:"Othr"`
}

// PhoneNumber ...
type PhoneNumber string

// PlainCardData10 ...
type PlainCardData10 struct {
	PAN       string        `json:"PAN"`
	CardSeqNb string        `json:"CardSeqNb"`
	FctvDt    string        `json:"FctvDt"`
	XpryDt    string        `json:"XpryDt"`
	SvcCd     string        `json:"SvcCd"`
	TrckData  []*TrackData1 `json:"TrckData"`
	CrdhldrNm string        `json:"CrdhldrNm"`
}

// PlusOrMinusIndicator ...
type PlusOrMinusIndicator bool

// PointOfInteractionCapabilities4 ...
type PointOfInteractionCapabilities4 struct {
	CardRdngCpblties      []string                `json:"CardRdngCpblties"`
	CardWrttgCpblties     []string                `json:"CardWrttgCpblties"`
	CrdhldrVrfctnCpblties []string                `json:"CrdhldrVrfctnCpblties"`
	PINLngthCpblties      float64                 `json:"PINLngthCpblties"`
	ApprvlCdLngth         float64                 `json:"ApprvlCdLngth"`
	MxScrptLngth          float64                 `json:"MxScrptLngth"`
	CardCaptrCpbl         bool                    `json:"CardCaptrCpbl"`
	OnLineCpblties        string                  `json:"OnLineCpblties"`
	MsgCpblties           []*DisplayCapabilities3 `json:"MsgCpblties"`
}

// PostalAddress1 ...
type PostalAddress1 struct {
	AdrTp       string   `json:"AdrTp"`
	AdrLine     []string `json:"AdrLine"`
	StrtNm      string   `json:"StrtNm"`
	BldgNb      string   `json:"BldgNb"`
	PstCd       string   `json:"PstCd"`
	TwnNm       string   `json:"TwnNm"`
	CtrySubDvsn string   `json:"CtrySubDvsn"`
	Ctry        string   `json:"Ctry"`
}

// PostalAddress18 ...
type PostalAddress18 struct {
	AdrLine     []string `json:"AdrLine"`
	StrtNm      string   `json:"StrtNm"`
	BldgNb      string   `json:"BldgNb"`
	PstCd       string   `json:"PstCd"`
	TwnNm       string   `json:"TwnNm"`
	CtrySubDvsn []string `json:"CtrySubDvsn"`
	Ctry        string   `json:"Ctry"`
}

// Recipient4Choice ...
type Recipient4Choice struct {
	KeyTrnsprt *KeyTransport4  `json:"KeyTrnsprt"`
	KEK        *KEK4           `json:"KEK"`
	KeyIdr     *KEKIdentifier2 `json:"KeyIdr"`
}

// Recipient5Choice ...
type Recipient5Choice struct {
	IssrAndSrlNb *IssuerAndSerialNumber1 `json:"IssrAndSrlNb"`
	KeyIdr       *KEKIdentifier2         `json:"KeyIdr"`
}

// RecurringTransaction2 ...
type RecurringTransaction2 struct {
	InstlmtPlan []string           `json:"InstlmtPlan"`
	PlanId      string             `json:"PlanId"`
	SeqNb       float64            `json:"SeqNb"`
	PrdUnit     string             `json:"PrdUnit"`
	InstlmtPrd  float64            `json:"InstlmtPrd"`
	TtlNbOfPmts float64            `json:"TtlNbOfPmts"`
	FrstPmtDt   string             `json:"FrstPmtDt"`
	TtlAmt      *CurrencyAndAmount `json:"TtlAmt"`
	FrstAmt     float64            `json:"FrstAmt"`
	Chrgs       float64            `json:"Chrgs"`
}

// RelativeDistinguishedName1 ...
type RelativeDistinguishedName1 struct {
	AttrTp  string `json:"AttrTp"`
	AttrVal string `json:"AttrVal"`
}

// Response3Code ...
type Response3Code string

// ResponseType2 ...
type ResponseType2 struct {
	Rslt         string `json:"Rslt"`
	RsltDtls     string `json:"RsltDtls"`
	AddtlRsltInf string `json:"AddtlRsltInf"`
}

// ResultDetail1Code ...
type ResultDetail1Code string

// SaleContext1 ...
type SaleContext1 struct {
	SaleId        string `json:"SaleId"`
	SaleRefNb     string `json:"SaleRefNb"`
	SaleRcncltnId string `json:"SaleRcncltnId"`
	CshrId        string `json:"CshrId"`
	ShftNb        string `json:"ShftNb"`
	AddtlSaleData string `json:"AddtlSaleData"`
}

// SupportedPaymentOption1Code ...
type SupportedPaymentOption1Code string

// Traceability3 ...
type Traceability3 struct {
	RlayId      *GenericIdentification74 `json:"RlayId"`
	TracDtTmIn  string                   `json:"TracDtTmIn"`
	TracDtTmOut string                   `json:"TracDtTmOut"`
}

// TrackData1 ...
type TrackData1 struct {
	TrckNb  string `json:"TrckNb"`
	TrckVal string `json:"TrckVal"`
}

// TransactionChannel3Code ...
type TransactionChannel3Code string

// TransactionEnvironment2Code ...
type TransactionEnvironment2Code string

// TransactionEnvironment3Code ...
type TransactionEnvironment3Code string

// TransactionIdentifier2 ...
type TransactionIdentifier2 struct {
	RcncltnDt string `json:"RcncltnDt"`
	RcncltnId string `json:"RcncltnId"`
}

// TransactionVerificationResult4 ...
type TransactionVerificationResult4 struct {
	Mtd        string `json:"Mtd"`
	VrfctnNtty string `json:"VrfctnNtty"`
	Rslt       string `json:"Rslt"`
	AddtlRslt  string `json:"AddtlRslt"`
}

// TrueFalseIndicator ...
type TrueFalseIndicator bool

// TypeOfAmount1Code ...
type TypeOfAmount1Code string

// TypeOfAmount5Code ...
type TypeOfAmount5Code string

// TypeOfAmount6Code ...
type TypeOfAmount6Code string

// TypeOfAmount7Code ...
type TypeOfAmount7Code string

// UPICIdentifier ...
type UPICIdentifier string

// UserInterface1Code ...
type UserInterface1Code string

// UserInterface3Code ...
type UserInterface3Code string

// Verification1Code ...
type Verification1Code string
